version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  consul:
    image: consul:1.13.2
    ports:
     - "8500:8500"
    command: agent -dev -client 0.0.0.0

volumes:
  elasticsearch-data:
  redis-data:
