package com.example.trade.goods.db.mappers;

import com.example.trade.goods.db.model.Goods;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Aug 02 21:13:39 EDT 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Aug 02 21:13:39 EDT 2023
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Aug 02 21:13:39 EDT 2023
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Aug 02 21:13:39 EDT 2023
     */
    Goods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Aug 02 21:13:39 EDT 2023
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Aug 02 21:13:39 EDT 2023
     */
    int updateByPrimaryKey(Goods record);

    int lockStock(Long id);

    int deductStock(Long id);

    int revertStock(Long id);

    int lockStockMulti(@Param("id") Long id, @Param("num") Integer num);

    int deductStockMulti(@Param("id") Long id, @Param("num") Integer num);

    int revertStockMulti(@Param("id") Long id, @Param("num") Integer num);
}